### ISSUE TITLE
Implement graph serialization.

### ISSUE THREAD

**Issue by ahmetaa** [ahmetaa/zemberek-nlp#10]

**Comment by s** [comment]
Hello, 
Currently I am wondering if I can build graph once and persist it via serialization so that in second or third times it won't need to rebuild whole graph again.
Also I wonder if there is an option to read from previous serialized data.

Thanks for the great work!
Said.

**Comment by ahmetaa** [comment]
@s this is not yet available. I do not like Java's object serialization so probably it will be a custom binary format - if we implement it. But this is a rather low priority issue. However, binary serialization of dictionary is an easier problem that may alleviate startup speed issues. I will consider at least implementing it in mid term. Current graph mechanism is unfortunately kind of broken, so I refrain myself working on it.

Also I am curious your use case, do you need this because you make a lot of instantiation?

**Comment by muratcorlu** [comment]
We tried to use zemberek in a AWS lambda function. As you may know, lambda functions instantly creates an instance by a trigger and after 10 minutes idle, it's closing. Now, it takes about 30 seconds to build graph for the first time. If we can cache it on disk or somewhere else we'll reach a big performance improvements.

**Comment by mdakin** [comment]
@muratcorlu  @s 

There are a few things going on here,

1. In general I don't advise to run zemberek on very short living instances. why don't you have a few always running zemberek instances and your functions just connects to those? There are other problems with this approach, zemberek internally uses a morphological analysis cache, if your instances keep dying you will not be able to utilize the cache. In the end,  even if you have serialization implemented and achieve sub second startup times (like old zemberek) I would not run it in this manner, zemberek is designed to run as a server.

2. 30 seconds is way too much, on my machine it was only a few seconds to initialize zemberek.

**Comment by mdakin** [comment]
@muratcorlu 
Having said that, if lambda stays up 10 mins, there are a few things you can do to use zemberek,
- Understand why it is taking 30 seconds to startup, no need to optimize something that is already fast.
- We can warm up the cache during startup with most used words (5-10K would be enough) for increased performance after startup
- Ahmet is working on a new morphological parser, it could have a faster startup because it does not generate surface graph
- Dictionaries could be serialized for fast startup
@ahmetaa  would say more about these, I am just a kibitzer.

**Comment by ahmetaa** [comment]
@mdakin According to my tests a cold start takes about 5 seconds, a warm start takes about 3 seconds with an SSD disk. My guess is that nature of AWS Lambda causes this slow down but I do not have any experience with it.

**Comment by muratcorlu** [comment]
We are trying to write a web service for zemberek. So we will have common service for our several projects that are written with several technologies. Because of the scalability issues, we tought aws lambda fits our needs. But maybe lambda is not a good environment for java projects. Maybe we should try app engine.

**Comment by s** [comment]
Hello, thank you for your replies @ahmetaa @mdakin . I liked the binary approach since the dictionaries and grammar rules don't change so often. Therefore we were considering generating the graph once and then reuse it and update it oftentimes like once in a week or something in that range.
I have relatively similar results with you guys on my local machine. But on lambda we got that 30 seconds unfortunately. 
As @muratcorlu stated, our main goal is to have a robust client to Zemberek and have it on a scalable infra so that it can be consumed by multiple resources usually in a use case of feature extraction or preprocessing phases of the projects.

**Comment by mdakin** [comment]
@muratcorlu I don't know about AWS or lambda, on GCE side, I would either create a Cloud endpoint (https://cloud.google.com/endpoints/docs/grpc) for a GRPC api, or maybe just an appengine flex deployment with some rest api, indeed there are other options. I started doing something like this in past, but never finished  it.

If you need raw performance, zemberek is quite fast, it is  also trivial to make it scale further on a multi cpu machine. I would give it its own instance.

**Comment by mdakin** [comment]
@muratcorlu @s We made initial steps to add serialization to Zemberek, it is not enabled yes, but my tests shows that creating root lexicon now takes ~200ms (instead of  > 1200ms) if serialized form is used. 
We are working on replacing the suffix graph with something more robust, and will serialize it as well when we are done, then zemberek will be more suitable to be used in a serverless environment.
related code is in https://github.com/ahmetaa/zemberek-nlp/blob/master/morphology/src/main/java/zemberek/morphology/lexicon/Serializer.java

**Comment by ahmetaa** [comment]
Although not exactly graph serialization, dictionary serialization is implemented in 0.12.0 (by mdakin). Closing.
