### ISSUE TITLE
could you please share ner model ? 

### ISSUE THREAD

**Issue by pasa13142** [ahmetaa/zemberek-nlp#241]
Is there any chance to share your ner model ?

**Comment by pasa13142** [comment]
How can we use name entity regocnition ?

**Comment by ahmetaa** [comment]
Since annotated NER data is not open source, we could not distribute NER models. Some data is available in the internet such as (http://haydut.isikun.edu.tr/nlptoolkit.html) . You can use it with the information from here https://github.com/ahmetaa/zemberek-nlp/tree/master/ner to generate your own model.
