### ISSUE TITLE
Are there any Turkish words database?

### ISSUE THREAD

**Issue by Rexota** [ahmetaa/zemberek-nlp#34]
Hey

Are there any Turkish words database?

I know one[url] in zemberek repo, but it's not suitable for me. I just need words, **not** like this:

aba
abacı
abacıya 

Url = https://code.google.com/p/zemberek/downloads/detail?name=full.txt.tr.tar.gz

**Comment by cnntogz** [comment]
Unfortunatelly. There is not any turkish word database like as wordnet
3 Ağu 2015 15:49 tarihinde "Rexota" <notifications@github.com> yazdı:

**Comment by ahmetaa** [comment]
Well there is a list here:

https://github.com/ahmetaa/zemberek-nlp/blob/master/morphology/src/main/resources/tr/master-dictionary.dict

Hope that it is what you needed.

**Comment by Rexota** [comment]
Ahmetaa, thank you very much. 

Really thanks.

**Comment by ahmetaa** [comment]
Rexota,

Keep in mind that you may need to clean the data. There are some
annotations like POS or some phonetic properties etc.
Not all words contain POS information, some are inferred. Such as if a word
does not contain POS but  ends with -mek or -mak it is a Verb , otherwise
it is  a noun..
There are some compound words, check how are they labeled.
Also there are some supplementary dictionaries (.dict) here:

https://github.com/ahmetaa/zemberek-nlp/tree/master/morphology/src/main/resources/tr

**Comment by Rexota** [comment]
Hey

Thanks for remind, I already cleaned the file but I will double check every word by manual. 

Good night.
