### ISSUE TITLE
Cannot parse Salih

### ISSUE THREAD

**Issue by sonerx** [ahmetaa/zemberek-nlp#75]
Salih is in person-names.dict but it cannot be parsed

**Comment by ahmetaa** [comment]
Reason is that person names file is not actually included as a default dictionary. I preferred adding proper names that are gathered from a corpus with some heuristics. They are in proper-from-corpus.dict. However, due to a limitation in the process, names that have other noun analyses, such as Salih, Gül etc. do not exist there. I am planning to add them. I still think proper names cannot be analyzed properly with dictionaries as they can be almost any word can be a surname and there are far too many proper names in the world.
